import type { Metadata } from "next";
import { Montserrat, Radio_Canada } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { AuthProvider } from "@/providers/AuthProvider";
import { FollowedGamesProvider } from "@/providers/FollowedGamesProvider";




const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

const radioCanada = Radio_Canada({
  subsets: ["latin"],
  variable: "--font-radio-canada",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${montserrat.variable} ${radioCanada.variable} antialiased bg-off-black text-off-white min-h-screen`}
      >
        <AuthProvider>
          <FollowedGamesProvider>
            <Header />
            <main>{children}</main>
            <Footer />
          </FollowedGamesProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
